- id: doi:10.1093/database/baac042
  type: paper
  date: 2022-1-1
  image: images/Mining Host-Pathogen Interactions from Biomedical Literature.jpg
  
- id: doi:10.1016/j.ijmedinf.2020.104351
  type: paper
  date: 2021-3-1
  image: images/A comprehensive study of mobility related function in clinical notes.jpg

- id: doi:10.1186/s12889-019-7630-3
  type: paper
  date: 2019-10-1
  image: images/Broadening horizons- the case for capturing function.jpeg
  
- id: doi:10.1093/bioinformatics/bts042
  type: paper
  date: 2012-1-27
  image: images/Literature mining of host-pathogen interactions- comparing feature-based supervised learning and language-based approaches.jpeg
  
- id: doi:10.1109/chase52844.2021.00024
  type: paper
  date: 2021-12-1
  image: images/A high-throughput, online tool-0000.jpg

- id: doi:10.1109/chase52844.2021.00031
  type: paper
  date: 2021-12-1
  image: images/Computer-assisted medical billing information extraction-0000.jpg

- id: doi:10.1007/978-3-030-82199-9_1
  type: paper
  date: 2021-8-7
  image: images/LexDivPara A Measure of Paraphrase Quality with Integrated Sentential Lexical Complexity.jpg

- id: doi:10.1109/bibm.2017.8218042
  type: paper
  date: 2017-11-1
  image: images/Inductive identification of functional status information-0000.jpg
  
- id: doi:10.5772/22016
  type: book
  date: 2011-9-15
  image: Mining Host-Pathogen Interactions.jpg

- id: doi:10.32469/10355/49119
  type: book
  image: images/Graphical Evolving Transformation System Machine.jpg
<<<<<<< Updated upstream
=======

- title: Phase II basket group sequential clinical trial with binary responses
  authors:
    - Wenxian Zhou
    - Ao Yuan
    - Thanh Thieu
    - Hong-Bin Fang
    - Ming T. Tan
  publisher: Austin Biometrics and Biostatistics
  date: 2017-1-1
  link: https://austinpublishinggroup.com/biometrics/fulltext/biometrics-v4-id1033.pdf

- title: "Characterizing the Language of Functioning: A Corpus Analysis Illustrating How Human Function is Described in Clinical Text"
  authors:
    - Denis Newman-Griffis
    - Thanh Thieu
    - Chunxiao Zhou
    - Diane Brandt
    - Jonathan C. Maldonado
    - Julia Porcino
    - Albert M. Lai
    - Leighton Chan
  publisher: AMIA Joint Summits on Translational Science, San Francisco, CA
  date: 2017-1-1
  link: https://www.academia.edu/32967524/Characterizing_the_Language_of_Functioning_A_Corpus_Analysis_Illustrating_How_Human_Function_is_Described_in_Clinical_Text

- title: Mining Host-Pathogen Interaction from Biomedical Literature
  authors:
    - Thanh Thieu
    - Dmitry Korkin
  publisher: University of Missouri - Columbia, USA
  date: 2011-1-1
>>>>>>> Stashed changes
