- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor sit amet_, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1093/database/baac042
  type: paper
  date: 2022-1-1
  image: images/Mining Host-Pathogen Interactions from Biomedical Literature.jpg
  
- id: doi:10.1016/j.ijmedinf.2020.104351
  type: paper
  date: 2021-3-1
  image: images/A comprehensive study of mobility related function in clinical notes.jpg

- id: doi:10.1186/s12889-019-7630-3
  type: paper
  date: 2019-10-1
  image: images/Broadening horizons- the case for capturing function.jpeg
  
- id: doi:10.1093/bioinformatics/bts042
  type: paper
  date: 2012-1-27
  image: images/Literature mining of host–pathogen interactions- comparing feature-based supervised learning and language-based approaches.jpeg
  
- id: doi:10.1109/chase52844.2021.00024
  type: paper
  date: 2021-12-1
  image: images/A high-throughput, online tool-0000.jpg

- id: doi:10.1109/chase52844.2021.00031
  type: paper
  date: 2021-12-1
  image: images/Computer-assisted medical billing information extraction-0000.jpg

- id: doi:10.1007/978-3-030-82199-9_1
  type: paper
  date: 2021-8-7
  image: images/LexDivPara A Measure of Paraphrase Quality with Integrated Sentential Lexical Complexity.jpg

- id: doi:10.1109/bibm.2017.8218042
  type: paper
  date: 2017-11-1
  image: images/Inductive identification of functional status information-0000.jpg

- id: doi:10.5772/22016
  type: book
  date: 2011-9-15
  image: Mining Host-Pathogen Interactions.jpg

- id: doi:10.32469/10355/49119
  type: book
  date: 
  image: images/Graphical Evolving Transformation System Machine.jpg

